AWSTemplateFormatVersion: '2010-09-09'
Description: 'Email Ingestion Infrastructure for Trade Alerts'

Parameters:
  Environment:
    Type: String
    Default: prod
    Description: Environment name (prod, staging, dev)
  
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing Lambda deployment package

Resources:
  # DynamoDB Table for Trade Alerts
  TradeAlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'trade-alerts-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: received_at
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ReceivedAtIndex
          KeySchema:
            - AttributeName: received_at
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'email-ingestion-lambda-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:gmail/api/credentials*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !GetAtt TradeAlertsTable.Arn
                  - !Sub '${TradeAlertsTable.Arn}/index/*'

  # Lambda Function
  EmailIngestionFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'email-ingestion-${Environment}'
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: email-ingestion.zip
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TradeAlertsTable
          ENVIRONMENT: !Ref Environment

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'email-ingestion-api-${Environment}'
      Description: 'API Gateway for email ingestion'
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: gmail

  # API Gateway Method
  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EmailIngestionFunction.Arn}/invocations'

  # Lambda Permission for API Gateway
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EmailIngestionFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/POST/gmail'

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref Environment

Outputs:
  ApiGatewayUrl:
    Description: 'API Gateway URL for email ingestion'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/gmail'
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayUrl'

  DynamoDBTableName:
    Description: 'DynamoDB table name for trade alerts'
    Value: !Ref TradeAlertsTable
    Export:
      Name: !Sub '${AWS::StackName}-DynamoDBTableName'

  LambdaFunctionName:
    Description: 'Lambda function name'
    Value: !Ref EmailIngestionFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName' 